ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
BOARD_TAG = teensy31
ARDMK_DIR = ../build_scripts
ARDUINO_LIBS = arduino-menusystem Adafruit_SSD1306 Audio SPI SerialFlash Wire Adafruit_GFX Bounce2 SD synth
USER_LIB_PATH = ../otamatone/libs
#F_CPU = 120000000
include ../build_scripts/Teensy.mk
