ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
BOARD_TAG = teensy31
ARDUINO_LIBS = MenuSystem Adafruit_SSD1306 Audio SPI SerialFlash Wire Adafruit_GFX Bounce2 SD
F_CPU = 120000000
include Teensy.mk
