ARDUINO_DIR = /Applications/Arduino.app/Contents/Java
BOARD_TAG = teensy31
ARDUINO_LIBS = arduino-menusystem Adafruit_SSD1306 Audio SPI SerialFlash Wire Adafruit_GFX Bounce2 SD
USER_LIB_PATH = ../src/libs/
F_CPU = 120000000
include Teensy.mk
